### ISSUE TITLE
normalization of ISBN 9783863267667

### ISSUE THREAD

**Issue by PeterMuellerr** [briandfoy/business-isbn-data#10]
Perling the code 
```
#!/usr/bin/perl -l
use Business::ISBN;
print Business::ISBN->new('9783863267667')->as_string;
```
spits out 978-3-86326-766-7. At the same time, the publisher typesets the ISBN of “[Moderne Betriebssysteme](https://www.pearson.de/moderne-betriebssysteme-9783863267667)” differently: 978-3-8632-6766-7.  I asked the [publisher](https://www.pearson.de/kontakt/kundenservice) around 2021-07-21 and the [International ISBN agency](https://www.isbn-international.org/content/about-us) on 2021-07-26.  Pearson has not answered so far, and the International ISBN agency said it would inform the German one. Which of the two spellings with hyphens is correct™?
Crosspost: https://github.com/briandfoy/business-isbn/issues/14 .

**Comment by briandfoy** [comment]
Looking at the published ranges from https://www.isbn-international.org/range_file_generation, the Perl module is correct. The ranges for the publisher codes are 7000-8499 and 85000-89999. There is no publisher code that is 8632 in the 3 group.

**Comment by PeterMuellerr** [comment]
Pearson corrected it on https://www.pearson.de/moderne-betriebssysteme-9783863267667
