### ISSUE TITLE
make_data.pl should not be shipped or should not load modules from 'lib'

### ISSUE THREAD

**Issue by atoomic** [briandfoy/business-isbn-data#3]
make_data.pl seems to be a non documented tool which is part of this distribution
we should either 
- do not ship it
- or if we consider it has useful value then we should not try to load file from unsafe locations and remove
` use lib qw(lib);`

**Comment by briandfoy** [comment]
I've replaced that line with the usual FindBin stuff (36a0dba84e32a53955ca7202db69243a0bed5923). Thanks,
